### PR TITLE
feat(cli): add check mode

### PR DESCRIPTION
**Pull request by uZer**
Hi!
I'd like to add a check mode in the CLI.
My motivation is to be able to run `liquidsoap-prettier -c <file>` in a CI job and return 2 if the file isn't formatted.

---

A bit unreleated:
I couln't test and run the code localy so I'm not sure it works, could you help me?
I tried to `npm install` and realized you were using ocaml `dune` tool I'm not familiar with. 
After installing `ocaml`, `dune`, `opam` and running `dune build` I'm failing because of missing libraries:

```
libraries js_of_ocaml liquidsoap-js liquidsoap-lang liquidsoap-lang.tooling
...
Hint: opam install js_of_ocaml-compiler
```

I ran `opam install js_of_ocaml` but it says I'm supposed to run `opam init` first, and the command is failing:
```
No configuration file found, using built-in defaults.
...
<><> Fetching repository information ><><><><><><><><><><><><><><><><><><><><><>
[ERROR] Could not update repository "default": Failed to extract archive /tmp/opam-1452103-014abd/index.tar.gz: "/usr/bin/tar xfz
        /tmp/opam-1452103-014abd/index.tar.gz -C /home/ypiolet/.opam/repo/default.new" exited with code 2
[ERROR] Initial download of repository failed.
```

I tried to install the ocaml deps with my distribution AUR packages too (Archlinux). But the package `aur/ocaml-js_of_ocaml` is broken too, probably due to main libraries version mismatch (`0.16.0` installed with archlinux packages, but this AUR package expects something `>=0.17.0`

```
-> No AUR package found for ocaml-base>=0.17.0
 -> No AUR package found for ocaml-base>=0.17.0
 -> No AUR package found for ocaml-stdio>=0.17.0
 -> No AUR package found for ocaml-sexplib0>=0.17.0
 -> No AUR package found for ocaml-stdio>=0.17.0
 -> could not find all required packages: ocaml-stdio >=0.17.0
could not find all required packages: ocaml-sexplib0 >=0.17.0
could not find all required packages: ocaml-base >=0.17.0
```

Well... I just wanted to add a check mode and `liquidsoap.cjs` is missing :D Do I have other alternatives to test locally?

### CODE REVIEW

**Comment by toots** [comment]
That's a great idea! The dependency on `dune` is annoying and can be avoided if you are only working on the javascript side of things.

I have just added: `npm run dev:prepare` which should download the compiled liquidsoap parser file from the latest published `npm` package so you can get rolling with the rest of the changes.

**Comment by uZer** [comment]
Thanks!
I think it's not better:
```
> liquidsoap-prettier@1.5.2 build:web
> webpack --config webpack.web.cjs

assets by status 34 KiB [cached] 1 asset
runtime modules 396 bytes 2 modules
orphan modules 48.2 KiB [orphan] 1 module
./src/index.js + 1 modules 67.4 KiB [built] [code generated]

ERROR in ./src/index.js 2:0-53
Module not found: Error: Can't resolve '../dist/liquidsoap.cjs' in '/home/ypiolet/ypi.github/liquidsoap-prettier/src'
resolve '../dist/liquidsoap.cjs' in '/home/ypiolet/ypi.github/liquidsoap-prettier/src'
  using description file: /home/ypiolet/ypi.github/liquidsoap-prettier/package.json (relative path: ./src)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: /home/ypiolet/ypi.github/liquidsoap-prettier/package.json (relative path: ./dist/liquidsoap.cjs)
      Field 'browser' doesn't contain a valid alias configuration
      /home/ypiolet/ypi.github/liquidsoap-prettier/dist/liquidsoap.cjs doesn't exist

webpack 5.92.1 compiled with 1 error in 604 ms
```

it's always this `dist/liquidsoap.cjs` that is missing!

**Comment by uZer** [comment]
Thanks!
It works now :)

**Comment by toots** [comment]
Looking good thanks!

**Pull request merged**
